apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: provisioned-namespace 
  janus-idp.io/tekton: provisioned-namespace
  backstage.io/kubernetes-id: provisioned-namespace
  backstage.io/kubernetes-namespace: provisioned-namespace 
  app.kubernetes.io/part-of: provisioned-namespace
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  