apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: provisioned-namespace
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: provisioned-namespace 
  name: provisioned-namespace
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: provisioned-namespace
    weight: 100 
